# Generated by Django 4.0.1 on 2022-02-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASSIGNIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AVAILABILITY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DINET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ELK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAMILY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FEATURES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LOCAL_OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LOCATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ORG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='STAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('assignip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.assignip')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.availability')),
                ('be', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.be')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.class')),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.con')),
                ('dinet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.dinet')),
                ('elk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.elk')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.family')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.features')),
                ('hv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.hv')),
                ('kes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.kes')),
                ('kna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.kna')),
                ('local_os', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.local_os')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.location')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.org')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.role')),
                ('ssh', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.ssh')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.stage')),
                ('wu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.wu')),
            ],
        ),
    ]
