# Generated by Django 4.0.1 on 2022-01-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hostname',
            new_name='name',
        ),
    ]
