# Generated by Django 3.2.12 on 2022-02-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0002_auto_20220210_0738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FEATURES',
            new_name='FEATURE',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='role',
            new_name='roles',
        ),
    ]
