# Generated by Django 4.0.1 on 2022-02-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0002_rename_hostname_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='assignip',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.assignip'),
        ),
        migrations.AddField(
            model_name='host',
            name='availability',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.availability'),
        ),
        migrations.AddField(
            model_name='host',
            name='be',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.be'),
        ),
        migrations.AddField(
            model_name='host',
            name='clas',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.class'),
        ),
        migrations.AddField(
            model_name='host',
            name='con',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.con'),
        ),
        migrations.AddField(
            model_name='host',
            name='dinet',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.dinet'),
        ),
        migrations.AddField(
            model_name='host',
            name='elk',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.elk'),
        ),
        migrations.AddField(
            model_name='host',
            name='family',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.family'),
        ),
        migrations.AddField(
            model_name='host',
            name='features',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.features'),
        ),
        migrations.AddField(
            model_name='host',
            name='hv',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.hv'),
        ),
        migrations.AddField(
            model_name='host',
            name='kes',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.kes'),
        ),
        migrations.AddField(
            model_name='host',
            name='kna',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.kna'),
        ),
        migrations.AddField(
            model_name='host',
            name='local_os',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.local_os'),
        ),
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.location'),
        ),
        migrations.AddField(
            model_name='host',
            name='role',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.role'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.ssh'),
        ),
        migrations.AddField(
            model_name='host',
            name='stage',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.stage'),
        ),
        migrations.AddField(
            model_name='host',
            name='wu',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.wu'),
        ),
        migrations.AlterField(
            model_name='host',
            name='org',
            field=models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.org'),
        ),
    ]
