# Generated by Django 3.2.12 on 2022-02-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0003_auto_20220211_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='var',
            old_name='name',
            new_name='var_type',
        ),
    ]
