# Generated by Django 3.2.12 on 2022-02-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0007_auto_20220216_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='tv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.tv'),
        ),
    ]
