# Generated by Django 3.2.12 on 2022-02-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0008_host_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='tv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ansible_admin_panel.tv'),
        ),
    ]
