# Generated by Django 3.2.12 on 2022-02-18 06:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0009_alter_host_tv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignip',
            options={'verbose_name_plural': 'ASSIGNIP'},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'AVAILABILITY'},
        ),
        migrations.AlterModelOptions(
            name='be',
            options={'verbose_name_plural': 'BE'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'CLASS'},
        ),
        migrations.AlterModelOptions(
            name='con',
            options={'verbose_name_plural': 'CON'},
        ),
        migrations.AlterModelOptions(
            name='dinet',
            options={'verbose_name_plural': 'DINET'},
        ),
        migrations.AlterModelOptions(
            name='elk',
            options={'verbose_name_plural': 'ELK'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'FAMILY'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'FEATURE'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'Host'},
        ),
        migrations.AlterModelOptions(
            name='hv',
            options={'verbose_name_plural': 'HV'},
        ),
        migrations.AlterModelOptions(
            name='kes',
            options={'verbose_name_plural': 'KES'},
        ),
        migrations.AlterModelOptions(
            name='kna',
            options={'verbose_name_plural': 'KNA'},
        ),
        migrations.AlterModelOptions(
            name='local_os',
            options={'verbose_name_plural': 'LOCAL OS'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'LOCATION'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name_plural': 'ORG'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'ROLE'},
        ),
        migrations.AlterModelOptions(
            name='ssh',
            options={'verbose_name_plural': 'SSH'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name_plural': 'STAGE'},
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name_plural': 'TV'},
        ),
        migrations.AlterModelOptions(
            name='var',
            options={'verbose_name_plural': 'Var'},
        ),
        migrations.AlterModelOptions(
            name='vartype',
            options={'verbose_name_plural': 'Var type'},
        ),
        migrations.AlterModelOptions(
            name='wu',
            options={'verbose_name_plural': 'WU'},
        ),
        migrations.AddField(
            model_name='var',
            name='json_value',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
