# Generated by Django 3.2.12 on 2022-02-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_admin_panel', '0010_auto_20220218_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='json_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
